name: EAS Build (Development)

on:
  push:
    branches:
      - '**'
  pull_request:
    types: [closed]
    branches:
      - develop
  workflow_dispatch:
    inputs:
      build_target:
        description: 'Which development build to run'
        required: true
        default: 'development-client'
        type: choice
        options:
          - development
          - development-client

jobs:
  build-development:
    if: github.event_name == 'pull_request' &&
        github.event.pull_request.merged == true &&
        github.base_ref == 'develop' &&
        contains(join(github.event.pull_request.labels.*.name), 'ios-build:development') ||
        github.event_name == 'workflow_dispatch' && github.event.inputs.build_target == 'development'
    runs-on: ubuntu-latest
    environment: Development
    steps:
      - name: ğŸ’» Checkout code 
        uses: actions/checkout@v4

      - name: ğŸ—ï¸ Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: ğŸ—ï¸ Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: ğŸ“¦ Install dependencies
        run: npm install

      - name: ğŸš€ Build iOS Development
        run: eas build --platform ios --profile development --non-interactive

  build-development-client:
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.build_target == 'development-client'
    environment: Development
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ’» Checkout code 
        uses: actions/checkout@v4

      - name: ğŸ—ï¸ Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: ğŸ—ï¸ Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: ğŸ“¦ Install dependencies
        run: npm install

      - name: ğŸš€ Build iOS Development Client
        run: eas build --platform ios --profile development-client --non-interactive