name: EAS Build (Development)

on:
  push:
    branches:
      - '**'
  pull_request:
    types: [closed]
    branches:
      - develop

jobs:
  build-development:
    if: github.event_name == 'pull_request' &&
        github.event.pull_request.merged == true &&
        github.base_ref == 'develop' &&
        contains(join(github.event.pull_request.labels.*.name), 'build-development')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - run: npm install -g eas-cli

      - run: eas login --token ${{ secrets.EAS_TOKEN }}

      - run: eas build --platform ios --profile development --non-interactive

  build-development-client:
    if: github.event_name == 'push' && contains(github.ref, '-client')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - run: npm install -g eas-cli

      - run: eas login --token ${{ secrets.EAS_TOKEN }}

      - run: eas build --platform ios --profile development-client --non-interactive

  build-development-test:
    if: github.event_name == 'push' && contains(github.ref, 'configuration')
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: ğŸ’» Checkout code 
        uses: actions/checkout@v4

      - name: ğŸ—ï¸ Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: ğŸ—ï¸ Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: ğŸ“¦ Install dependencies
        run: npm install

      - name: ğŸš€ Build iOS Development
        run: eas build --platform ios --profile development --non-interactive